PIPELINE:
  # Set to run pipeline on a Windows machine
#  PDFTOTEXT_PATH: '/Users/rajratnpranesh/Score/xpdf-tools-linux-4.03/bin64/pdftotext'
  FEATURES:
    - 'doi'
    - 'title'
    - 'num_citations'
    - 'author_count'
    - 'sjr'
    - 'u_rank'
    - 'self_citations'
    - 'upstream_influential_methodology_count'
    - 'subject'
    - 'subject_code'
    - 'citationVelocity'
    - 'influentialCitationCount'
    - 'references_count'
    - 'openaccessflag'
    - 'normalized_citations'
    - 'influentialReferencesCount'
    - 'reference_background'
    - 'reference_result'
    - 'reference_methodology'
    - 'citations_background'
    - 'citations_result'
    - 'citations_methodology'
    - 'citations_next'
    - 'coCite2'
    - 'coCite3'
    - 'reading_score'
    - 'subjectivity'
    - 'sentiment'
    - 'num_hypo_tested'
    - 'real_p'
    - 'real_p_sign'
    - 'p_val_range'
    - 'num_significant'
    - 'sample_size'
    - "extend_p"
    - "funded"
    - 'avg_pub'
    - 'avg_hidx'
    - 'avg_auth_cites'
    - 'avg_high_inf_cites'
    - 'sentiment_agg'
    - 'age'
    - 'Venue_Citation_Count'
    - "Venue_Scholarly_Output"
    - "Venue_Percent_Cited"
    - "Venue_CiteScore"
    - "Venue_SNIP"
    - "Venue_SJR"
    - "Venue_subject_code"
    - "Venue_subject"

APP:
  AUTH:
    USER: 'darpa_score'
    PASSWORD: 'sCoRe'
  TRAINING:
    WEIGHTS_PATH: 'Market/output/train_api'
    IDENTIFIER_FIELDS:
      - 'doi'
      - 'title'
      - 'paper_id'
